### ISSUE TITLE
Colliding with bs-css

### ISSUE THREAD

**Issue by nikgraf** [minima-app/re-css#7]
I was migrating a UI lib from bs-css to bs-emotion and noticed when having both in the project compilation fails. Do you think the interface can be fixed to avoid this issue? Otherwise migration from one to the other has to happen in one go, which makes transition way harder in larger projects

```
>>>> Start compiling
[2/2] Building packages/button/src/Button.mlast.d
[1/3] Building packages/button/src/Button-Ui.cmj

  We've found a bug for you!
  /projects/ui/packages/button/src/Button.re
  
  It's possible that your build is stale.
  Try to clean the artifacts and build again?
  
  Here's the original error message
  The files /projects/ui/node_modules/bs-emotion/lib/ocaml/emotion.cmi
  and /projects/ui/node_modules/bs-css/lib/ocaml/css.cmi
  make inconsistent assumptions over interface Css
```

**Comment by alex35mil** [comment]
Ah, that's unfortunate. I'll think how to deal w/ such case but I'm not sure if it's possible w/o renaming `Css.re` to something else. Maybe there's some `bsc` flag for this or something.

**Comment by alex35mil** [comment]
Or maybe I can just `include Css` in `bs-emotion` instead of opening it and it shouldn't be exposed + it won't be necessary to install `re-css`. I'll try it out tomorrow.

**Comment by alex35mil** [comment]
Ok I managed that to work. It's adds up a bit to maintenance cost but should be feasible. I need to clean things up a bit, then I'll cut a release.

**Comment by alex35mil** [comment]
Published `bs-emotion@0.0.7`. Should work after update. Also, don't forget to remove `re-css` direct dependency.

**Comment by nikgraf** [comment]
cool, thx!

**Comment by nikgraf** [comment]
worked like a charm https://github.com/reactvienna/ui/pull/15

**Comment by alex35mil** [comment]
Awesome!
